=== kubosis/ISEP-SemanticWeb-Project/labs/lab01/ex5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="universityCourses" type="universityCourseType">
        <xs:key name="courseKey">
        <xs:selector xpath="course"/>
        <xs:field xpath="@code"/>
    </xs:key>

    <xs:keyref name="prereqKeyRef" refer="courseKey">
        <xs:selector xpath="course/prerequisites/course"/>
        <xs:field xpath="."/>
    </xs:keyref>
    </xs:element>
    <xs:element name="course" type="courseType"/>
    <xs:element name="prerequisites" type="prereqType"/>

    <xs:complexType name="universityCourseType">
        <xs:sequence>
            <xs:element name="course" type="courseType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>



    <xs:complexType name="prereqType">
        <xs:sequence>
            <xs:element name="course" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="courseType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="professor" type="xs:string"/>
            <xs:element name="keyword" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="prerequisites" type="prereqType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="code" type="xs:string"/>
        <xs:attribute name="credits" type="xs:integer"/>
    </xs:complexType>
</xs:schema>

=== kubosis/ISEP-SemanticWeb-Project/labs/lab01/ex5.xml
<?xml version="1.0" encoding="UTF-8"?>
<universityCourses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ex5.xsd">

<course code="ABC" credits="3">
    <title>Semantic Web and Knowledge Management</title>
    <description>This course covers RDF, OWL, SPARQL, and knowledge graph construction.</description>
    <professor>Dr. Emily Chen</professor>
    <keyword>RDF</keyword>
    <keyword>OWL</keyword>
    <keyword>SPARQL</keyword>
</course>

<course code="ML1" credits="4">
    <title>Machine learning 1</title>
    <description>This course covers basics of ml.</description>
    <professor>Dr. Max Muller</professor>
    <keyword>ML</keyword>
</course>

<course code="ML2" credits="4">
    <title>Machine learning 2</title>
    <description>This course covers advanced topics of ml.</description>
    <professor>Dr. Max Muller</professor>
    <keyword>ML</keyword>
    <prerequisites>
        <course>ML1</course>
    </prerequisites>
</course>

</universityCourses>
